WebApp/Models/LoginForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class LoginForm
    {
        [Display(Name = "Email")]
        [Required]
        public string Email { get; set; }

        [Display(Name = "Heslo")]
        [Required]
        public string Password { get; set; }
    }
}

WebApp/Models/RegisterForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class RegisterForm
    {
        [Display(Name = "Jméno")]
        [Required]
        public string FirstName { get; set; }

        [Display(Name = "Příjmení")]
        [Required]
        public string LastName { get; set; }

        [Display(Name = "Email")]
        [Required]
        public string Email { get; set; }

        [Display(Name = "Heslo")]
        [Required]
        public string Password { get; set; }

        
    }
}

WebApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Lib.DomainLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class LoginController : Controller
    {

        public IActionResult Index()
        {
            ViewBag.isLogged = false;
            string login = HttpContext.Session.GetString("Email");
            if (!string.IsNullOrEmpty(login))
            {
                ViewBag.isLogged = true;
                ViewBag.Email = login;
            }
            return View();
        }

        [HttpPost]
        public IActionResult Index(LoginForm logForm)
        {
            if (ModelState.IsValid)
            {
                if (UserAuthentication.Login(logForm.Email, logForm.Password))
                {
                    //HttpContext.Session.SetString("user", logInfo.Login);
                    HttpContext.Session.SetString("Email", logForm.Email);
                    return RedirectToAction("Index", "Home");
                    //return RedirectToAction("Index", new RouteValueDictionary( new { controller = Home, action = "Index", auth = ea }));
                }
                else
                {
                    ModelState.AddModelError("Email", logForm.Email);
                    ModelState.AddModelError("Password", logForm.Password);
                   
                }
                
            }
            return View();
        }


        public IActionResult Register(RegisterForm form)
        {
            if (ModelState.IsValid)
            {
                if (!Regex.IsMatch(form.FirstName, @"^[a-zA-Z]+$"))
                {
                    ModelState.AddModelError("FirstName", "Název může obsahovat pouze znaky");
                }
            }

            if (ModelState.IsValid)
            {
                if (!Regex.IsMatch(form.LastName, @"^[a-zA-Z]+$"))
                {
                    ModelState.AddModelError("LastName", "Název může obsahovat pouze znaky");
                }
            }

            if (ModelState.IsValid)
            {
                if (!Regex.IsMatch(form.Email, @"[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}"))
                {
                    ModelState.AddModelError("Email", "Email není platný");
                }
            }

            if (ModelState.IsValid)
            {

                if (Lib.DomainLayer.User.GetByEmail(form.Email) == null)
                {
                    Lib.DomainLayer.User user = new User()
                    {
                        FirstName = form.FirstName,
                        LastName = form.LastName,
                        Email = form.Email,
                        Password = form.Password
                    };
                    user.Insert();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

WebApp/Views/Login/Index.cshtml
@model LoginForm
@{
    ViewData["Title"] = "Index";
}


    <div>
        <h2 style="align-items:center;">Přihlášení</h2>

        @using (Html.BeginForm())
        {
            <p>
                @Html.LabelFor(x => x.Email)
                @Html.TextBoxFor(x => x.Email)
                @Html.ValidationMessageFor(x => x.Email)
            </p>
            <p>
                @Html.LabelFor(x => x.Password)
                @Html.PasswordFor(x => x.Password)
                @Html.ValidationMessageFor(x => x.Password)
            </p>
            <button type="submit" class="button"> Přihlásit se </button>
        }
        <li><a asp-area="" asp-controller="Login" asp-action="Register">Registrace</a></li>
    </div>

WebApp/Views/Login/Register.cshtml
@model RegisterForm
@{
    ViewData["Title"] = "Registrace";
}


    <div>
        <h2 style="align-items:center;">Registrace</h2>

        @using (Html.BeginForm())
        {
            <p>
                @Html.LabelFor(x => x.FirstName)
                @Html.TextBoxFor(x => x.FirstName)
                @Html.ValidationMessageFor(x => x.FirstName)
            </p>
            <p>
                @Html.LabelFor(x => x.LastName)
                @Html.TextBoxFor(x => x.LastName)
                @Html.ValidationMessageFor(x => x.LastName)
            </p>
            <p>
                @Html.LabelFor(x => x.Email)
                @Html.TextBoxFor(x => x.Email)
                @Html.ValidationMessageFor(x => x.Email)
            </p>
            <p>
                @Html.LabelFor(x => x.Password)
                @Html.PasswordFor(x => x.Password)
                @Html.ValidationMessageFor(x => x.Password)
            </p>
            <button type="submit" class="button"> Registrace </button>
        }
    </div>